version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: .
    binary: custos
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/timkrebs/custos/version.Version={{.Version}}
      - -X github.com/timkrebs/custos/version.GitCommit={{.Commit}}
      - -X github.com/timkrebs/custos/version.GitTreeState=clean
      - -X github.com/timkrebs/custos/version.BuildDate={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: timkrebs
    name: custos
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
