title: Custos
description: The missing terraform plan for HashiCorp Vault policies.
url: "https://timkrebs.github.io"
baseurl: "/custos"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

permalink: pretty

exclude:
  - DEVELOPMENT_WORKFLOW.md
  - Gemfile
  - Gemfile.lock
